version: '3.7'
services:
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  statistics:
    build:
      context: .
      dockerfile: app.Dockerfile
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://user:password@db:5432/stats
    depends_on:
      - db